apiVersion: v1
kind: Pod
metadata:
   name: conf-file
   labels:
      app: wordpress
spec:
   containers:
   - name: con1
     image: httpd:latest
     ports:
     - containerPort: 80
     volumeMounts:
     - name: myvol
       mountPath: /usr/local/apache2/htdocs 
   volumes:
   - name: myvol
     configMap:
        name: httpindex
---
apiVersion: v1
kind: Service
metadata:
   name: mypod-svc
spec:
   type: NodePort
   selector:
      app: wordpress
   ports:
   - port: 80
     nodePort: 30123

---
apiVersion: v1
data:
  index.html: |
    <h1> Hello, From ConfigMap !!!!</h1>
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: httpindex
