apiVersion: v1
kind: Pod
metadata:
   name: pass-file
   labels:
      app: wordpress
spec:
   containers:
   - name: con1
     image: httpd:latest
     ports:
     - containerPort: 80
     volumeMounts:
     - name: myvol
       mountPath: /data
   volumes:
   - name: myvol
     secret:
       secretName: passfile 
---
apiVersion: v1
kind: Service
metadata:
   name: mypod-svc
spec:
   type: NodePort
   selector:
      app: wordpress
   ports:
   - port: 80
     nodePort: 30123

