FROM ubuntu:18.04
RUN apt update && apt install apache2 wget unzip -y
ADD web.tgz /var/www/html
WORKDIR /var/www/html
RUN mkdir -p /var/run/apache2
RUN chown -R www-data:www-data /var/run/apache2
RUN chown -R www-data:www-data /var/log/apache2/
EXPOSE 80
user www-data
CMD ["/usr/sbin/apache2ctl","-D","FOREGROUND"]
