apiVersion: v1
kind: Pod
metadata:
   name: mydb
   labels:
      app: mysql
spec:
   containers:
   - name: con1
     image: mysql:5.7
     env:
     - name: MYSQL_ROOT_PASSWORD
       value: test123
     - name: MYSQL_DATABASE
       value: wordpress
     ports:
     - containerPort: 3306

---
apiVersion: v1
kind: Service
metadata:
   name: mydb-svc
spec:
   selector:
      app: mysql
   ports:
   - port: 3306

