apiVersion: v1
kind: Pod
metadata:
   name: wordpress
   labels:
      app: wordpress
spec:
   containers:
   - name: con1
     image: wordpress:latest
     env:
     - name: WORDPRESS_DB_HOST
       value: mydb-svc
     - name: WORDPRESS_DB_USER
       value: root
     - name: WORDPRESS_DB_PASSWORD
       value: test123
     - name: WORDPRESS_DB_NAME
       value: wordpress
     - name: WORDPRESS_TABLE_PREFIX
       value: wp1_ 
     ports:
     - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
   name: mypod-svc
spec:
   type: NodePort
   selector:
      app: wordpress
   ports:
   - port: 80
     nodePort: 30123
