apiVersion: v1
kind: Pod
metadata:
   name: mypod
   labels:
      app: myapp
spec:
   volumes:
   - name: myvol
     emptyDir: {}
   containers:
   - name: con1
     image: httpd:latest
     ports:
     - containerPort: 80
     volumeMounts:
     - name: myvol
       mountPath: /data
   - name: con2
     image: tomcat:latest
     ports:
     - containerPort: 3306
     volumeMounts:
     - name: myvol
       mountPath: /mylogs



