apiVersion: apps/v1
kind: DaemonSet
metadata:
   name: mydaemon-set
spec:
   selector:
      matchLabels:
        app: myapp1
   template:
      metadata:
         labels:
           app: myapp1
      spec:
         containers:
         - name: con1
           image: nginx:latest
           ports:
           - containerPort: 80
#         nodeSelector:
#            cpu: ryzen
         tolerations:
         - key:  node-role.kubernetes.io/master
           effect: NoSchedule
