apiVersion: apps/v1
kind: Deployment
metadata:
   name: mydep
spec:
   replicas: 3
   selector:
      matchLabels:
        app: myapp1
   template:
      metadata:
         labels:
           app: myapp1
      spec:
         containers:
         - name: con1
           image: nginx:latest
           ports:
           - containerPort: 80


---
apiVersion: v1
kind: Service
metadata:
   name: mydep-svc
spec:
   type: NodePort
   selector:
      app: myapp1
   ports:
   - port: 80
     nodePort: 30125
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: mydep
spec:
  maxReplicas: 10
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mydep
  targetCPUUtilizationPercentage: 70
