apiVersion: v1
kind: Pod
metadata:
   name: mypod
   labels:
      app: myapp
spec:
   containers:
   - name: con1
     image: wordpress:latest
     ports:
     - containerPort: 80
#     resources:
#       limits:
#         memory: "512Mi"
#         cpu: "1m"
#       requests:
#         memory: "128Mi"
#         cpu: "0.5m"
     livenessProbe:
       exec:
        command:
        - cat 
        - /var/www/html/index.php
       initialDelaySeconds: 20
       periodSeconds: 5
   - name: con2
     image: mysql:5.7
     env:
     - name: MYSQL_ROOT_PASSWORD
       value: test123
     - name: MYSQL_DATABASE
       value: wordpress
     ports:
     - containerPort: 3306


---
apiVersion: v1
kind: Service
metadata:
   name: mypod-svc
spec:
   type: NodePort
   selector:
      app: myapp
      env: dev
   ports:
   - port: 80
     nodePort: 30123
