apiVersion: v1
kind: Pod
metadata:
   name: mypod-readi-tcp
   labels:
      app: myapp
      env: dev
spec:
   containers:
   - name: con1
     image: httpd:latest
     ports:
     - containerPort: 80
#     resources:
#       limits:
#         memory: "512Mi"
#         cpu: "1m"
#       requests:
#         memory: "128Mi"
#         cpu: "0.5m"
     readinessProbe:
       tcpSocket:
         port: 80
       initialDelaySeconds: 20
       periodSeconds: 5
   - name: con2
     image: mysql:5.7
     env:
     - name: MYSQL_ROOT_PASSWORD
       value: test123
     - name: MYSQL_DATABASE
       value: wordpress
     ports:
     - containerPort: 3306


