apiVersion: v1
kind: Pod
metadata:
   name: mypod
   labels:
      app: myapp
spec:
   containers:
   - name: con1
     image: wordpress:latest
     ports:
     - containerPort: 80
#   nodeName: node1 
   nodeSelector:
       cpu: ryzen
